dist: xenial
sudo: required
language: java
install: mvn install -DskipTests=true -Dgpg.skip=true
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8
  - openjdk11
services:
  - docker
before_script:
  - docker run -e TZ=Europe/Moscow -d -p 127.0.0.1:8123:8123 --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:latest
